id = "squirrel"
name = "Squirrel"
version = "0.1.0"
schema_version = 1
authors = ["Taliesin Perscilla Ambroise <talunion72@gmail.com>"]
description = "Squirrel language support for Zed"
repository = "https://github.com/FlutterTal/zed-squirrel"

[language_servers.squirrel_language_server]
name = "Squirrel Language Server"
language = "Squirrel"

[grammars.squirrel]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-squirrel"
commit = "072c969749e66f000dba35a33c387650e203e96e"
